[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 10.5

[font.offset]
y = 3

[colors.primary]
background = "#000000"
foreground = "#d7d7d7"

[colors.normal]
black   = "#000000"
red     = "#a83f45"
green   = "#43a66f"
yellow  = "#b9b85f"
blue    = "#4d75a8"
magenta = "#9c63a8"
cyan    = "#4f9bad"
white   = "#c8c8c8"

[colors.bright]
black   = "#555555"
red     = "#c4565d"
green   = "#5fbd87"
yellow  = "#d1cf78"
blue    = "#668dc0"
magenta = "#b476bd"
cyan    = "#68b1c4"
white   = "#d7d7d7"

[window]
startup_mode = "Maximized"
decorations = "None"

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 200
lines = 50

[selection]
save_to_clipboard = true

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

[cursor.style]
blinking = "Never"
